platform :ios, '6.0'
pod 'FMDBx', '~> 0.2.0'
pod 'IQKeyboardManager', '~> 3.2.1.0'
pod 'UMengAnalytics-NO-IDFA', '~> 3.4.5' 
pod 'iOS-Hierarchy-Viewer', '~> 1.4.7'
pod 'AdsMoGo-iOS-Lib',:path=>'/Users/chenshaojie/Desktop/project/AdsMoGo-iOS-Lib'